#############################################################################
# Makefile for building: madingley
# Generated by qmake (2.01a) (Qt 4.8.5) on: Fri Nov 6 10:16:45 2015
# Project:  madingley.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile madingley.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -w -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I../Madingley/Model_structure -I../Madingley/Utility_classes -I../Madingley/Ecological_processes_cohorts -I../Madingley/Ecological_processes_cohorts/Technical_code -I../Madingley/Output_and_tracking -I../Madingley/Ecological_processes_cohorts/Dispersal_implementations/Technical_code -I../Madingley/Ecological_processes_cohorts/Eating_implementations/Technical_code -I../Madingley/Ecological_processes_cohorts/Metabolism_implementations/Technical_code -I../Madingley/Ecological_processes_cohorts/Mortality_implementations/Technical_code -I../Madingley/Ecological_processes_cohorts/Reproduction_implementations/Technical_code -I../NetCDFIO/src -I/usr/local/netcdfcxx-4.2.1/include -I/usr/local/netcdfc-4.3.3.1/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/local/netcdfcxx-4.2.1/lib64 -L/usr/local/netcdfc-4.3.3.1/lib64 -L/usr/local/hdf-1.8.15/lib64 -L/usr/local/zlib-1.2.8/lib64 -L/usr/lib64 -lnetcdf_c++4 -lnetcdf -lhdf5_hl -lhdf5 -lcurl -lz -ldl -lQtGui -L/usr/lib64 -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Model_structure/Program.cc \
		Model_structure/Stock.cc \
		Model_structure/Cohort.cc \
		../NetCDFIO/src/Convertor.cpp \
		../NetCDFIO/src/DataGrid.cpp \
		../NetCDFIO/src/FileReader.cpp \
		../NetCDFIO/src/NcGridCell.cpp \
		../NetCDFIO/src/Logger.cpp 
OBJECTS       = Program.o \
		Stock.o \
		Cohort.o \
		Convertor.o \
		DataGrid.o \
		FileReader.o \
		NcGridCell.o \
		Logger.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		madingley.pro
QMAKE_TARGET  = madingley
DESTDIR       = 
TARGET        = madingley

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: madingley.pro  /usr/share/qt4/mkspecs/default/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -o Makefile madingley.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile madingley.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/madingley1.0.0 || $(MKDIR) .tmp/madingley1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/madingley1.0.0/ && $(COPY_FILE) --parents Model_structure/MadingleyModelInitialisation.h Model_structure/MadingleyModel.h Model_structure/ModelGrid.h Utility_classes/Properties.h Utility_classes/Stopwatch.h .tmp/madingley1.0.0/ && $(COPY_FILE) --parents Model_structure/Program.cc Model_structure/Stock.cc Model_structure/Cohort.cc ../NetCDFIO/src/Convertor.cpp ../NetCDFIO/src/DataGrid.cpp ../NetCDFIO/src/FileReader.cpp ../NetCDFIO/src/NcGridCell.cpp ../NetCDFIO/src/Logger.cpp .tmp/madingley1.0.0/ && (cd `dirname .tmp/madingley1.0.0` && $(TAR) madingley1.0.0.tar madingley1.0.0 && $(COMPRESS) madingley1.0.0.tar) && $(MOVE) `dirname .tmp/madingley1.0.0`/madingley1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/madingley1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

Program.o: Model_structure/Program.cc ../Madingley/Model_structure/MadingleyModel.h \
		../Madingley/Model_structure/MadingleyModelInitialisation.h \
		../Madingley/Utility_classes/UtilityFunctions.h \
		../Madingley/Model_structure/FunctionalGroupDefinitions.h \
		../Madingley/Model_structure/EnviroData.h \
		../Madingley/Utility_classes/MassBinsHandler.h \
		../Madingley/Model_structure/ModelGrid.h \
		../Madingley/Model_structure/GridCellCohortHandler.h \
		../Madingley/Model_structure/Cohort.h \
		../Madingley/Model_structure/GridCell.h \
		../Madingley/Model_structure/GridCellStockHandler.h \
		../Madingley/Model_structure/Stock.h \
		../Madingley/Utility_classes/ClimateVariablesCalculator.h \
		../Madingley/Model_structure/RevisedTerrestrialPlantModel.h \
		../Madingley/Output_and_tracking/GlobalProcessTracker.h \
		../Madingley/Output_and_tracking/ProcessTracker.h \
		../Madingley/Utility_classes/Stopwatch.h \
		../Madingley/Model_structure/CohortMerge.h \
		../Madingley/Ecological_processes_cohorts/Dispersal.h \
		../Madingley/Ecological_processes_cohorts/Dispersal_implementations/Technical_code/IDispersalImplementation.h \
		../Madingley/Ecological_processes_cohorts/Dispersal_implementations/Technical_code/TAdvectiveDispersal.h \
		../Madingley/Ecological_processes_cohorts/Dispersal_implementations/Technical_code/TResponsiveDispersal.h \
		../Madingley/Ecological_processes_cohorts/Dispersal_implementations/Technical_code/TDiffusiveDispersal.h \
		../Madingley/Model_structure/EcologyStock.h \
		../Madingley/Model_structure/AutotrophProcessor.h \
		../Madingley/Model_structure/HANPP.h \
		../Madingley/Model_structure/EcologyCohort.h \
		../Madingley/Model_structure/ApplyEcology.h \
		../Madingley/Ecological_processes_cohorts/Technical_code/IEcologicalProcessWithinGridCells.h \
		../Madingley/Model_structure/ThreadLocked.h \
		../Madingley/Ecological_processes_cohorts/Eating_implementations/Technical_code/IEatingImplementation.h \
		../Madingley/Ecological_processes_cohorts/Eating.h \
		../Madingley/Ecological_processes_cohorts/Eating_implementations/Technical_code/TRevisedPredation.h \
		../Madingley/Ecological_processes_cohorts/Eating_implementations/Technical_code/TRevisedHerbivory.h \
		../Madingley/Ecological_processes_cohorts/Reproduction.h \
		../Madingley/Ecological_processes_cohorts/Reproduction_implementations/Technical_code/IReproductionImplementation.h \
		../Madingley/Ecological_processes_cohorts/Reproduction_implementations/Technical_code/TReproductionBasic.h \
		../Madingley/Ecological_processes_cohorts/Mortality.h \
		../Madingley/Ecological_processes_cohorts/Mortality_implementations/Technical_code/IMortalityImplementation.h \
		../Madingley/Ecological_processes_cohorts/Mortality_implementations/Technical_code/TBackgroundMortality.h \
		../Madingley/Ecological_processes_cohorts/Mortality_implementations/Technical_code/TSenescenceMortality.h \
		../Madingley/Ecological_processes_cohorts/Mortality_implementations/Technical_code/TStarvationMortality.h \
		../Madingley/Ecological_processes_cohorts/Metabolism.h \
		../Madingley/Ecological_processes_cohorts/Metabolism_implementations/Technical_code/IMetabolismImplementation.h \
		../Madingley/Ecological_processes_cohorts/Metabolism_implementations/Technical_code/TMetabolismHeterotroph.h \
		../Madingley/Ecological_processes_cohorts/Metabolism_implementations/Technical_code/TMetabolismEndotherm.h \
		../Madingley/Ecological_processes_cohorts/Metabolism_implementations/Technical_code/TMetabolismEctotherm.h \
		../Madingley/Ecological_processes_cohorts/Activity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Program.o Model_structure/Program.cc

Stock.o: Model_structure/Stock.cc ../Madingley/Model_structure/RevisedTerrestrialPlantModel.h \
		../Madingley/Output_and_tracking/GlobalProcessTracker.h \
		../Madingley/Output_and_tracking/ProcessTracker.h \
		../Madingley/Model_structure/GridCellStockHandler.h \
		../Madingley/Model_structure/Stock.h \
		../Madingley/Model_structure/FunctionalGroupDefinitions.h \
		../Madingley/Utility_classes/UtilityFunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stock.o Model_structure/Stock.cc

Cohort.o: Model_structure/Cohort.cc ../Madingley/Model_structure/Cohort.h \
		../Madingley/Model_structure/GridCell.h \
		../Madingley/Model_structure/GridCellStockHandler.h \
		../Madingley/Model_structure/Stock.h \
		../Madingley/Model_structure/FunctionalGroupDefinitions.h \
		../Madingley/Model_structure/GridCellCohortHandler.h \
		../Madingley/Utility_classes/ClimateVariablesCalculator.h \
		../Madingley/Model_structure/RevisedTerrestrialPlantModel.h \
		../Madingley/Output_and_tracking/GlobalProcessTracker.h \
		../Madingley/Output_and_tracking/ProcessTracker.h \
		../Madingley/Utility_classes/UtilityFunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cohort.o Model_structure/Cohort.cc

Convertor.o: ../NetCDFIO/src/Convertor.cpp ../NetCDFIO/src/Convertor.h \
		../NetCDFIO/src/Types.h \
		../NetCDFIO/src/Logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Convertor.o ../NetCDFIO/src/Convertor.cpp

DataGrid.o: ../NetCDFIO/src/DataGrid.cpp ../NetCDFIO/src/DataGrid.h \
		../NetCDFIO/src/Types.h \
		../NetCDFIO/src/NcGridCell.h \
		../NetCDFIO/src/Logger.h \
		../NetCDFIO/src/Convertor.h \
		../NetCDFIO/src/Constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataGrid.o ../NetCDFIO/src/DataGrid.cpp

FileReader.o: ../NetCDFIO/src/FileReader.cpp ../NetCDFIO/src/FileReader.h \
		../NetCDFIO/src/Types.h \
		../NetCDFIO/src/Constants.h \
		../NetCDFIO/src/Logger.h \
		../NetCDFIO/src/Convertor.h \
		../NetCDFIO/src/DataGrid.h \
		../NetCDFIO/src/NcGridCell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileReader.o ../NetCDFIO/src/FileReader.cpp

NcGridCell.o: ../NetCDFIO/src/NcGridCell.cpp ../NetCDFIO/src/NcGridCell.h \
		../NetCDFIO/src/Types.h \
		../NetCDFIO/src/Constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NcGridCell.o ../NetCDFIO/src/NcGridCell.cpp

Logger.o: ../NetCDFIO/src/Logger.cpp ../NetCDFIO/src/Logger.h \
		../NetCDFIO/src/Types.h \
		../NetCDFIO/src/FileWriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Logger.o ../NetCDFIO/src/Logger.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/madingley/ || $(MKDIR) $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/madingley/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/madingley/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/madingley/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/madingley/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/madingley/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/ || $(MKDIR) $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/ 
	-$(INSTALL_FILE) /data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/Model_structure/Program.cc $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/
	-$(INSTALL_FILE) /data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/Model_structure/Stock.cc $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/
	-$(INSTALL_FILE) /data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/Model_structure/Cohort.cc $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/
	-$(INSTALL_FILE) /data/mb425/Madingley/madingley-ecosystem-model-old-cc/NetCDFIO/src/Convertor.cpp $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/
	-$(INSTALL_FILE) /data/mb425/Madingley/madingley-ecosystem-model-old-cc/NetCDFIO/src/DataGrid.cpp $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/
	-$(INSTALL_FILE) /data/mb425/Madingley/madingley-ecosystem-model-old-cc/NetCDFIO/src/FileReader.cpp $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/
	-$(INSTALL_FILE) /data/mb425/Madingley/madingley-ecosystem-model-old-cc/NetCDFIO/src/NcGridCell.cpp $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/
	-$(INSTALL_FILE) /data/mb425/Madingley/madingley-ecosystem-model-old-cc/NetCDFIO/src/Logger.cpp $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/
	-$(INSTALL_FILE) /data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/Model_structure/MadingleyModelInitialisation.h $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/
	-$(INSTALL_FILE) /data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/Model_structure/MadingleyModel.h $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/
	-$(INSTALL_FILE) /data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/Model_structure/ModelGrid.h $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/
	-$(INSTALL_FILE) /data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/Utility_classes/Properties.h $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/
	-$(INSTALL_FILE) /data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/Utility_classes/Stopwatch.h $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/Program.cc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/Stock.cc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/Cohort.cc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/Convertor.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/DataGrid.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/FileReader.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/NcGridCell.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/Logger.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/MadingleyModelInitialisation.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/MadingleyModel.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/ModelGrid.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/Properties.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/Stopwatch.h
	-$(DEL_DIR) $(INSTALL_ROOT)/data/mb425/Madingley/madingley-ecosystem-model-old-cc/Madingley/.:./Model_structure/ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

